{
    "targets": [
        {
            "target_name": "node-av",
            "sources": [
                "src/bindings/index.cc",
                "src/bindings/packet.cc",
                "src/bindings/frame.cc",
                "src/bindings/frame_async.cc",
                "src/bindings/frame_sync.cc",
                "src/bindings/codec.cc",
                "src/bindings/codec_context.cc",
                "src/bindings/codec_context_async.cc",
                "src/bindings/codec_context_sync.cc",
                "src/bindings/codec_parameters.cc",
                "src/bindings/codec_parser.cc",
                "src/bindings/format_context.cc",
                "src/bindings/format_context_async.cc",
                "src/bindings/format_context_sync.cc",
                "src/bindings/stream.cc",
                "src/bindings/dictionary.cc",
                "src/bindings/input_format.cc",
                "src/bindings/input_format_async.cc",
                "src/bindings/input_format_sync.cc",
                "src/bindings/output_format.cc",
                "src/bindings/io_context.cc",
                "src/bindings/io_context_async.cc",
                "src/bindings/io_context_sync.cc",
                "src/bindings/error.cc",
                "src/bindings/software_scale_context.cc",
                "src/bindings/software_scale_context_async.cc",
                "src/bindings/software_scale_context_sync.cc",
                "src/bindings/software_resample_context.cc",
                "src/bindings/software_resample_context_async.cc",
                "src/bindings/software_resample_context_sync.cc",
                "src/bindings/filter.cc",
                "src/bindings/filter_context.cc",
                "src/bindings/filter_context_async.cc",
                "src/bindings/filter_context_sync.cc",
                "src/bindings/filter_graph.cc",
                "src/bindings/filter_graph_async.cc",
                "src/bindings/filter_graph_sync.cc",
                "src/bindings/filter_graph_segment.cc",
                "src/bindings/filter_inout.cc",
                "src/bindings/hardware_device_context.cc",
                "src/bindings/hardware_frames_context.cc",
                "src/bindings/hardware_frames_context_async.cc",
                "src/bindings/hardware_frames_context_sync.cc",
                "src/bindings/log.cc",
                "src/bindings/utilities.cc",
                "src/bindings/audio_fifo.cc",
                "src/bindings/audio_fifo_async.cc",
                "src/bindings/audio_fifo_sync.cc",
                "src/bindings/fifo.cc",
                "src/bindings/fifo_async.cc",
                "src/bindings/fifo_sync.cc",
                "src/bindings/frame_utils.cc",
                "src/bindings/bitstream_filter.cc",
                "src/bindings/bitstream_filter_context.cc",
                "src/bindings/bitstream_filter_context_async.cc",
                "src/bindings/bitstream_filter_context_sync.cc",
                "src/bindings/option.cc",
                "src/bindings/sync_queue.cc",
                "src/bindings/device.cc",
                "src/bindings/device_sync.cc",
                "src/bindings/device_async.cc",
                "src/bindings/device_darwin.mm",
                "src/bindings/gpu_texture_darwin.mm",
                "externals/jellyfin-ffmpeg/fftools/sync_queue.c",
            ],
            "include_dirs": [
                "<!@(node -p \"require('node-addon-api').include\")",
                "/opt/ffbuild/prefix/include",
                "<(module_root_dir)/externals/jellyfin-ffmpeg",
                "<(module_root_dir)/externals/jellyfin-ffmpeg/libavcodec",
            ],
            "library_dirs": ["/opt/ffbuild/prefix/lib"],
            "dependencies": ["<!(node -p \"require('node-addon-api').gyp\")"],
            "cflags!": ["-fno-exceptions"],
            "cflags_cc!": ["-fno-exceptions"],
            "defines": ["NAPI_DISABLE_CPP_EXCEPTIONS"],
            "libraries": [
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavformat.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavcodec.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavfilter.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavutil.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswscale.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswresample.a",
                "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavdevice.a",
                "-L/opt/ffbuild/prefix/lib",
                "/opt/ffbuild/prefix/lib/libdav1d.a",
                "/opt/ffbuild/prefix/lib/libwebp.a",
                "/opt/ffbuild/prefix/lib/libwebpmux.a",
                "/opt/ffbuild/prefix/lib/libz.a",
                "-liconv",
                "-framework CoreFoundation",
                "-framework CoreVideo",
                "-framework CoreMedia",
                "-framework CoreServices",
                "-framework Security",
                "-framework Foundation",
            ],
            "xcode_settings": {
                "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
                "CLANG_CXX_LIBRARY": "libc++",
                "CLANG_CXX_LANGUAGE_STANDARD": "c++17",
                "MACOSX_DEPLOYMENT_TARGET": "12.0",
                "GCC_SYMBOLS_PRIVATE_EXTERN": "YES",
                "OTHER_CPLUSPLUSFLAGS": [
                    "-fexceptions",
                    "-fvisibility=hidden",
                    "-fvisibility-inlines-hidden",
                    "-O3",
                ],
                "OTHER_LDFLAGS": [
                    "-Wl,-dead_strip",
                    "-Wl,-no_warn_duplicate_libraries",
                    "-Wl,-exported_symbol,_napi_register_module_v1",
                ],
                "CONDITIONS": [
                    ["target_arch=='x64'", {"ARCHS": ["x86_64"]}],
                    ["target_arch=='arm64'", {"ARCHS": ["arm64"]}],
                ],
            },
        }
    ]
}
