{
    "targets": [
        {
            "target_name": "node-av",
            "sources": [
                "src/bindings/index.cc",
                "src/bindings/packet.cc",
                "src/bindings/frame.cc",
                "src/bindings/frame_async.cc",
                "src/bindings/frame_sync.cc",
                "src/bindings/codec.cc",
                "src/bindings/codec_context.cc",
                "src/bindings/codec_context_async.cc",
                "src/bindings/codec_context_sync.cc",
                "src/bindings/codec_parameters.cc",
                "src/bindings/codec_parser.cc",
                "src/bindings/format_context.cc",
                "src/bindings/format_context_async.cc",
                "src/bindings/format_context_sync.cc",
                "src/bindings/stream.cc",
                "src/bindings/dictionary.cc",
                "src/bindings/input_format.cc",
                "src/bindings/input_format_async.cc",
                "src/bindings/input_format_sync.cc",
                "src/bindings/output_format.cc",
                "src/bindings/io_context.cc",
                "src/bindings/io_context_async.cc",
                "src/bindings/io_context_sync.cc",
                "src/bindings/error.cc",
                "src/bindings/software_scale_context.cc",
                "src/bindings/software_scale_context_async.cc",
                "src/bindings/software_scale_context_sync.cc",
                "src/bindings/software_resample_context.cc",
                "src/bindings/software_resample_context_async.cc",
                "src/bindings/software_resample_context_sync.cc",
                "src/bindings/filter.cc",
                "src/bindings/filter_context.cc",
                "src/bindings/filter_context_async.cc",
                "src/bindings/filter_context_sync.cc",
                "src/bindings/filter_graph.cc",
                "src/bindings/filter_graph_async.cc",
                "src/bindings/filter_graph_sync.cc",
                "src/bindings/filter_graph_segment.cc",
                "src/bindings/filter_inout.cc",
                "src/bindings/hardware_device_context.cc",
                "src/bindings/hardware_frames_context.cc",
                "src/bindings/hardware_frames_context_async.cc",
                "src/bindings/hardware_frames_context_sync.cc",
                "src/bindings/log.cc",
                "src/bindings/utilities.cc",
                "src/bindings/audio_fifo.cc",
                "src/bindings/audio_fifo_async.cc",
                "src/bindings/audio_fifo_sync.cc",
                "src/bindings/fifo.cc",
                "src/bindings/fifo_async.cc",
                "src/bindings/fifo_sync.cc",
                "src/bindings/frame_utils.cc",
                "src/bindings/scaler.cc",
                "src/bindings/scaler_async.cc",
                "src/bindings/scaler_sync.cc",
                "src/bindings/bitstream_filter.cc",
                "src/bindings/bitstream_filter_context.cc",
                "src/bindings/bitstream_filter_context_async.cc",
                "src/bindings/bitstream_filter_context_sync.cc",
                "src/bindings/option.cc",
                "src/bindings/sync_queue.cc",
                "src/bindings/device.cc",
                "src/bindings/device_sync.cc",
                "src/bindings/device_async.cc",
                "externals/jellyfin-ffmpeg/fftools/sync_queue.c",
            ],
            "include_dirs": [
                "<!@(node -p \"require('node-addon-api').include\")",
                "<(module_root_dir)/externals/jellyfin-ffmpeg",
                "<(module_root_dir)/externals/jellyfin-ffmpeg/libavcodec",
            ],
            "dependencies": ["<!(node -p \"require('node-addon-api').gyp\")"],
            "cflags!": ["-fno-exceptions"],
            "cflags_cc!": ["-fno-exceptions"],
            "defines": ["NAPI_DISABLE_CPP_EXCEPTIONS", "NODE_API_SWALLOW_UNTHROWABLE_EXCEPTIONS"],
            "conditions": [
                [
                    "OS=='mac'",
                    {
                        "sources": [
                            "src/bindings/device_darwin.mm",
                            "src/bindings/gpu_texture_darwin.mm",
                        ],
                        "include_dirs": [
                            "/opt/ffbuild/prefix/include",
                        ],
                        "library_dirs": ["/opt/ffbuild/prefix/lib"],
                        "libraries": [
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavformat.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavcodec.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavfilter.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavutil.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswscale.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libswresample.a",
                            "-Wl,-force_load,/opt/ffbuild/prefix/lib/libavdevice.a",
                            "-L/opt/ffbuild/prefix/lib",
                            "/opt/ffbuild/prefix/lib/libdav1d.a",
                            "/opt/ffbuild/prefix/lib/libwebp.a",
                            "/opt/ffbuild/prefix/lib/libwebpmux.a",
                            "/opt/ffbuild/prefix/lib/libz.a",
                            "-liconv",
                            "-framework CoreFoundation",
                            "-framework CoreVideo",
                            "-framework CoreMedia",
                            "-framework CoreServices",
                            "-framework Security",
                            "-framework Foundation",
                        ],
                        "xcode_settings": {
                            "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
                            "CLANG_CXX_LIBRARY": "libc++",
                            "CLANG_CXX_LANGUAGE_STANDARD": "c++17",
                            "MACOSX_DEPLOYMENT_TARGET": "12.0",
                            "GCC_SYMBOLS_PRIVATE_EXTERN": "YES",
                            "OTHER_CPLUSPLUSFLAGS": [
                                "-fexceptions",
                                "-fvisibility=hidden",
                                "-fvisibility-inlines-hidden",
                                "-O3",
                            ],
                            "OTHER_LDFLAGS": [
                                "-Wl,-dead_strip",
                                "-Wl,-no_warn_duplicate_libraries",
                                "-Wl,-exported_symbol,_napi_register_module_v1",
                            ],
                            "CONDITIONS": [
                                ["target_arch=='x64'", {"ARCHS": ["x86_64"]}],
                                ["target_arch=='arm64'", {"ARCHS": ["arm64"]}],
                            ],
                        },
                    },
                ],
                [
                    "OS=='linux'",
                    {
                        "sources": [
                            "src/bindings/device_linux.cc",
                            "src/bindings/gpu_texture_linux.cc",
                        ],
                        "include_dirs": [
                            "/opt/ffbuild/prefix/include",
                        ],
                        "library_dirs": ["/opt/ffbuild/prefix/lib"],
                        "libraries": [
                            "-L/opt/ffbuild/prefix/lib",
                            "-Wl,--whole-archive",
                            "-Wl,--start-group",
                            "/opt/ffbuild/prefix/lib/libavdevice.a",
                            "/opt/ffbuild/prefix/lib/libavfilter.a",
                            "/opt/ffbuild/prefix/lib/libavformat.a",
                            "/opt/ffbuild/prefix/lib/libavcodec.a",
                            "/opt/ffbuild/prefix/lib/libswscale.a",
                            "/opt/ffbuild/prefix/lib/libswresample.a",
                            "/opt/ffbuild/prefix/lib/libavutil.a",
                            "/opt/ffbuild/prefix/lib/libdav1d.a",
                            "/opt/ffbuild/prefix/lib/libwebp.a",
                            "/opt/ffbuild/prefix/lib/libwebpmux.a",
                            "/opt/ffbuild/prefix/lib/libsharpyuv.a",
                            "/opt/ffbuild/prefix/lib/libz.a",
                            "/opt/ffbuild/prefix/lib/libiconv.a",
                            "-Wl,--end-group",
                            "-Wl,--no-whole-archive",
                            "-lpthread",
                            "-lm",
                            "-ldl",
                            "-lrt",
                            "-latomic",
                            "-lstdc++",
                        ],
                        "cflags": [
                            "-fvisibility=hidden",
                        ],
                        "cflags_cc": [
                            "-std=c++17",
                            "-fexceptions",
                            "-fvisibility=hidden",
                            "-fvisibility-inlines-hidden",
                            "-O3",
                        ],
                        "ldflags": [
                            "-Wl,-Bsymbolic",
                            "-Wl,-rpath,'$$ORIGIN'",
                            "-Wl,--allow-multiple-definition",
                            "-Wl,--exclude-libs,ALL",
                        ],
                    },
                ],
                [
                    "OS=='win' or (OS!='mac' and OS!='linux')",  # Mingw
                    {
                        "sources": [
                            "src/bindings/device_win32.cc",
                            "src/bindings/gpu_texture_win.cc",
                        ],
                        "conditions": [
                            [
                                "target_arch=='x64'",
                                {
                                    "include_dirs": [
                                        "/clang64/ffbuild/include",
                                    ],
                                    "library_dirs": ["/clang64/ffbuild/lib"],
                                },
                            ],
                            [
                                "target_arch=='arm64'",
                                {
                                    "include_dirs": [
                                        "/clangarm64/ffbuild/include",
                                    ],
                                    "library_dirs": ["/clangarm64/ffbuild/lib"],
                                },
                            ],
                        ],
                        "libraries": [
                            "-Wl,-Bstatic",
                            "-l:libavformat.a",
                            "-l:libavcodec.a",
                            "-l:libavfilter.a",
                            "-l:libavdevice.a",
                            "-l:libavutil.a",
                            "-l:libswscale.a",
                            "-l:libswresample.a",
                            "-l:libdav1d.a",
                            "-l:libwebp.a",
                            "-l:libwebpmux.a",
                            "-l:libwebpdemux.a",
                            "-l:libsharpyuv.a",
                            "-l:libz.a",
                            "-lpthread",
                            "-Wl,-Bdynamic",
                            "-lole32",
                            "-loleaut32",
                            "-lshlwapi",
                            "-lws2_32",
                            "-lstrmiids",
                            "-lmfuuid",
                            "-lpsapi",
                        ],
                        "cflags": [
                            "-fvisibility=hidden",
                        ],
                        "cflags_cc": [
                            "-std=c++17",
                            "-fexceptions",
                            "-fvisibility=hidden",
                            "-fvisibility-inlines-hidden",
                            "-O3",
                        ],
                        "ldflags": [
                            "-static-libgcc",
                            "-static-libstdc++",
                            "-Wl,--gc-sections",
                        ],
                    },
                ],
            ],
        }
    ]
}
